version: '3.3'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    networks: 
      - mongo-compose-network
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 9000:9000
    networks: 
      - mongo-compose-network
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    command: bash -c "node dbcreation.js && node userparse.js && node listingparses.js && node reviewsparse.js && node server.js"
    depends_on:
      - mongodb
 
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    restart: always
    ports:
      - 8080:8080
    networks: 
    - mongo-compose-network
    command: "npm run serve"
 
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks: 
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    restart: unless-stopped
  
networks:
  mongo-compose-network:
    driver: bridge